module DriftBatch

using DelimitedFiles
using JSON
using PyPlot
using Printf

# Include DriftDiagnostics
include("DriftDiagnostics.jl")
using .DriftDiagnostics

export batch_analyze_drift, plot_drift_results

"""
    batch_analyze_drift(vpmout::String, list_file::String, out_csv::String)

Reads a list of pulsars from `list_file`, finds their output directories in `vpmout`,
loads the single-pulse data and parameters, and runs `analyze_drift`.
Saves the results to `out_csv`.
"""
function batch_analyze_drift(vpmout::String, list_file::String, out_csv::String="drift_classifications.csv")
    if !isfile(list_file)
        error("Pulsar list file not found: $list_file")
    end

    names = String[]
    for line in eachline(list_file)
        s = strip(line)
        (isempty(s) || startswith(s, "#")) && continue
        push!(names, String(first(split(s))))
    end
    
    println("Found $(length(names)) pulsars in list.")
    
    results = []
    
    for (i, name) in enumerate(names)
        # Directory resolution fallback (check all 4 possible variations)
        candidates = [
            joinpath(vpmout, name * "_16"),
            vpmout * name * "_16",
            joinpath(vpmout, name),
            vpmout * name
        ]
        outdir = ""
        for cand in candidates
            if isdir(cand)
                outdir = cand
                break
            end
        end
        
        if isempty(outdir)
            @warn "[$i/$(length(names))] Skipping $name — Output dir not found. Checked: $(candidates[1]) etc."
            continue
        end
        
        params_file = joinpath(outdir, "params.json")
        debase_file = joinpath(outdir, "pulsar.debase.txt")
        
        missing_files = filter(!isfile, [params_file, debase_file])
        if !isempty(missing_files)
            missing_str = join(basename.(missing_files), ", ")
            @warn "[$i/$(length(names))] Skipping $name — required files missing in $outdir: $missing_str"
            continue
        end
        
        # Load params to get bin_st and bin_end
        params = JSON.parsefile(params_file)
        bin_st = get(params, "bin_st", 1)
        bin_end = get(params, "bin_end", nothing)
        
        # Load data matrix
        try
            X = readdlm(debase_file, Float64)
            if bin_end === nothing
                bin_end = size(X, 2)
            end
            
            println("[$i/$(length(names))] Analyzing $name ...")
            res = analyze_drift(X, bin_st, bin_end)
            
            push!(results, (name, res.travel_sig, res.asymmetry_ratio, res.phase_gradient, res.mean_peak_lag, res.score, res.classification))
            
        catch e
            @warn "[$i/$(length(names))] Failed to analyze $name: $e"
        end
    end
    
    # Save to CSV
    open(out_csv, "w") do io
        write(io, "Name,Travel_Sig,Asymmetry_Ratio,Phase_Gradient,Mean_Peak_Lag,Score,Classification\n")
        for r in results
            write(io, "$(r[1]),$(r[2]),$(r[3]),$(r[4]),$(r[5]),$(r[6]),$(r[7])\n")
        end
    end
    println("\nSaved results to $out_csv")
    return out_csv
end

"""
    plot_drift_results(csv_file::String, out_plot::String="drift_plot.png")

Reads the CSV generated by `batch_analyze_drift` and creates a scatter plot 
to visually separate amplitude-modulated pulsars from drifting pulsars.
"""
function plot_drift_results(csv_file::String, out_plot::String="drift_plot.png")
    data, header = readdlm(csv_file, ',', header=true)
    
    names = data[:, 1]
    asym = convert(Vector{Float64}, data[:, 3])
    grad = convert(Vector{Float64}, data[:, 4])
    lags = convert(Vector{Float64}, data[:, 5])
    classes = data[:, 7]
    
    # Setup plot
    PyPlot.figure(figsize=(10, 8))
    
    # Separate by class for coloring
    idx_am = classes .== "amplitude_modulation"
    idx_drift = classes .== "pure_drift"
    idx_bi = classes .== "bi_drift"
    idx_undef = classes .== "undetermined"
    
    # Scatter: X = Asymmetry (2DFS), Y = Phase Gradient (Cross-Spec)
    PyPlot.scatter(abs.(asym[idx_am]), abs.(grad[idx_am]), color="red", label="Amplitude Modulation (P3-only)", alpha=0.7, s=60)
    PyPlot.scatter(abs.(asym[idx_drift]), abs.(grad[idx_drift]), color="blue", label="Pure Drift", alpha=0.7, s=60)
    PyPlot.scatter(abs.(asym[idx_bi]), abs.(grad[idx_bi]), color="green", label="Bi-Drift", alpha=0.7, s=60)
    PyPlot.scatter(abs.(asym[idx_undef]), abs.(grad[idx_undef]), color="gray", label="Undetermined", alpha=0.7, s=40, marker="x")
    
    # Add labels for extreme cases (optional, could get crowded)
    for i in 1:length(names)
        if classes[i] == "pure_drift" && (abs(asym[i]) > 0.3 || abs(grad[i]) > 0.3)
            PyPlot.annotate(names[i], (abs(asym[i]), abs(grad[i])), fontsize=8, alpha=0.6)
        end
    end
    
    PyPlot.xlabel("|2DFS Asymmetry Ratio|")
    PyPlot.ylabel("|Cross-Spectrum Phase Gradient|")
    PyPlot.title("Subpulse Modulation Diagnostics")
    
    PyPlot.axhline(0.1, color="gray", linestyle="--", alpha=0.5)
    PyPlot.axvline(0.1, color="gray", linestyle="--", alpha=0.5)
    
    PyPlot.legend()
    PyPlot.grid(true, alpha=0.3)
    
    PyPlot.savefig(out_plot, dpi=300, bbox_inches="tight")
    PyPlot.close()
    
    println("Saved classification chart to $out_plot")
end

end # module
